OfflineMusic/urls.py
from django.contrib import admin
from django.conf.urls import include#, url
from django.urls import path
# from OfflinePlaylist import views

app_name = 'OfflinePlaylist'

urlpatterns = [
    path('', include('OfflinePlaylist.urls', namespace='index')),
    path('OFflinePlaylist/', include('OfflinePlaylist.urls')),
    path('admin/', admin.site.urls),
    # path('test/', include('OfflinePlaylist.urls', namespace='test')),
    # path('GetPlaylists/', include('OfflinePlaylist.urls', namespace='get_playlists')),
]

OfflinePlaylist/urls.py
# from django.conf.urls import url
from django.urls import path
from OfflinePlaylist import views

app_name = 'OfflinePlaylist'

urlpatterns = [
    path('', views.index, name="index"),
    path('playlist/', views.playlists, name='playlists'),
    path('test/', views.test, name='test'),
    path('GetPlaylists/', views.get_playlist, name='GetPlaylists'),
    path('song/<int:pk>', views.song_view, name='curr_song')
]

templates/GetPlaylists.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Get Playlist</title>
</head>
<body>
    <div style="height:30px">
        <button><a href="{% url 'OfflinePlaylist:index' %}">Search songs</a></button>
    </div>
    <form action="" method="POST">
        {% csrf_token %}
        <div class="OptionSelect" style="width:100%;">
            <div class="Select" style="width:100%;">
                <button type="submit" name="CurrentUser" style="width:13%; height:100%; float:left;">Get Current User Playlists</button>
                <button type="button" onclick="getPlaylistId()" style="width:13%; height:100%; float:left;">Playlist Id</button>
                <button type="button" onclick="getUserId()" style="width:13%; height:100%; float:left;">User Id</button>
            </div>
            <div class="UserIdInput" style="width: 100%; float:left; display: none;">
                <label for="UserID" style="float:left;">User Id :</label>
                <input type="text" name="UserId" style="width:25%; float:left;">
                <button type="submit" name="SelectUser" style="width:7%; height:100%; float:left;">Get User</button>
            </div>
            <div class="PlaylistIdInput" style="width: 100%; float:left; display: none;">
                <label for="PlaylistID" style="float:left;">Playlist Id :</label>
                <input type="text" name="PlaylistId" style="width:25%; float:left;">
                <button type="submit" name="SelectPlaylist" style="width:7%; height:100%; float:left;">Get Playlist</button>
            </div>
        </div>
        {% if playlists|length > 0 %}
            <div class="contianter" style="width:100%; float:left;">
                <div style="width: 20%; float: left;" class="PlasylistDisplay">
                    <h2>Playlists</h2>
                    <div class="list">
                    {% for playlist in playlists %}
                        <li class="listItem" name="listItem"> <button class="ViewPlaylist" name="ViewPlaylist" value="{{ playlist.id }}" type="submit"> {{ playlist.name }} </button> </li>
                    {% endfor %}
                    </div>
                </div>
                {% if songs|length > 0 %}
                    <div style="display:none;">
                        <input type="hidden" name="PlaylistName" value="{{playlistItem.name}}">
                        <input type="hidden" name="ID" value="{{playlistItem.id}}">
                    </div>
                    <div style="width: 80%; float: right;" class="SongDisplay">
                        {% if songs|length > 0 %}
                        <h2>Playlist: {{ playlistItem.name }}</h2>
                        <h3>Name - Artist - Album</h3>
                        <div style="height: 15px;">
                            <div style="width:20%; float:left;">
                                <input type="checkbox" id="select-all">
                                <label for="Songs">Select All</label>
                            </div>
                            <div style="width:80%; float:left;">
                                <label>Add this playlist: </label>
                                <button type="submit" name="AddPlaylist">Add</button>
                            </div>
                        </div>
                        {% for song in songs %}
                            <ul style="list-style-type: none;">
                                <li style="width:100%">
                                <div class="SongItem" style="width: 100%; height: 20px; margin:0; padding:3;">
                                    <p class="SongId" style="margin:0;">     
                                        <input type="checkbox" name="checkedSongs" value="{{song.id}}">{{song.name}} - {{song.artist}} - {{song.album}}
                                    </p>
                                </div>
                                </li>
                            </ul>
                        {% endfor %}
                        {% else %}
                            <!-- <h2>Playlist View</h2> -->
                            <h4>No songs yet...!!</h4>
                        {% endif %}
                    </div>
                {% endif %}
            </div>
        {% endif %}
    </form>
    <script>
        function getUserId()
        {
            var a = document.getElementsByClassName('UserIdInput')[0]
            a.style.display = 'block';
            var b = document.getElementsByClassName('PlaylistIdInput')[0]
            b.style.display = 'none';
        }

        function getPlaylistId()
        {
            var a = document.getElementsByClassName('UserIdInput')[0]
            a.style.display = 'none';
            var b = document.getElementsByClassName('PlaylistIdInput')[0]
            b.style.display = 'block';
        }

        document.getElementById('select-all').onclick = function() {
        var checkboxes = document.getElementsByName('checkedSongs');
        for (var checkbox of checkboxes) {
            checkbox.checked = this.checked;
        }
        }


    </script>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
    <style> 
        /*add full-width input fields*/ 
        /* input[type=text], 
        input[type=password] { 
            width: 100%; 
            padding: 12px 20px; 
            margin: 8px 0; 
            display: inline-block; 
            border: 2px solid #ccc; 
            box-sizing: border-box;  
        } */
        /* set a style for all buttons*/ 
        /* button { 
            background-color: green; 
            color: white; 
            padding: 14px 20px; 
            margin: 8px 0; 
            cursor: pointer; 
            width: 100%; 
        }  */
        /*set styles for the cancel button*/ 
        /* .cancelbtn { 
            padding: 14px 20px; 
            background-color: #FF2E00;  
        } */
        /*float cancel and signup buttons and add an equal width*/ 
        .cancelbtn, 
        .AddSong{ 
            float: left; 
            width: 50% 
        } 
        /*add padding to container elements*/ 
        .container { 
            padding: 16px; 
        } 
        /*define the modal’s background*/ 
          
        .modal { 
            display: none; 
            position: fixed; 
            z-index: 1; 
            left: 0; 
            top: 0; 
            width: 100%; 
            height: 100%; 
            overflow: auto; 
            background-color: rgb(0, 0, 0); 
            background-color: rgba(0, 0, 0, 0.8); 
            padding-top: 60px; 
        } 
        /*define the modal-content background*/ 
        
        .modal-content { 
            background-color: #fefefe; 
            margin: 5% auto 15% auto; 
            border: 1px solid #888; 
            width: 80%; 
        } 
        /*define the close button*/ 
          
        /* .close { 
            position: absolute; 
            right: 35px; 
            top: 15px; 
            color: #000; 
            font-size: 40px; 
            font-weight: bold; 
        }  */
        /*define the close hover and focus effects*/ 
          
        /* .close:hover, 
        .close:focus { 
            color: red; 
            cursor: pointer; 
        }  */
          
        .clearfix::after { 
            content: ""; 
            clear: both; 
            display: table; 
        }
    
        .playlists { 
            border:2px solid #ccc;
            width:300px;
            height: 100px;
            overflow-y: scroll; 
        } 
          
        /* @media screen and (max-width: 300px) { 
            .cancelbtn, 
            .signupbtn { 
                width: 100%; 
            } 
        }*/
    </style> 

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Search</title>
</head>
<body>
    <div style="height:30px">
        <a href="{% url 'OfflinePlaylist:GetPlaylists' %}"><button>Spotify Playlists</button></a>
        <a href="{% url 'OfflinePlaylist:playlists' %}"><button>Local Playlists</button></a>
    </div>
    
    <h1>Search Page</h1>
    <form action="" method="POST">
    {% csrf_token %}
        <div class = "category_div">
            <label for="Options"> Select out of the 3 : </label>
            <select name="categoryOption" >
                <option value="Track">Track</option>
                <option value="Artist">Artist</option>
                <option value="Album">Album</option>
            </select>
            <br><br>
        </div>
        
        <div class="Search">

            <label for="Search">Enter the name here </label>
            <input type="text" name="Input">
            <br><br>
            <button class="selectCategory" name="selectCategory" type="submit">Search</button>
        </div>

        {% if restart != True %}
            {% if category.name == 'Track' %}
                <div>
                    <h2>Name - Artist - Album</h2>

                        {% for track in tracks %}
                            <li class='track_item'>
                                <label for="{{ track.id }}"></label>
                                <p><input type="checkbox" class="checkedTracks" name="checkedTracks" id="{{ track.id }}" value="{{ track.id }}">{{ track.name }} - {{ track.artist }} - {{ track.album }}</p>
                            </li>
                        {% endfor %}
                </div>
                <button type="button" onclick=OpenPopUp() style="width:auto;">Add Songs to Playlist</button> 

            {% elif category.name == 'Artist'%}
                <div>
                    <h3>Artists</h3>
                        {% for artist in artists %}
                            <li class='artist_item'>
                                <label for="{{ track.id }}"></label>
                                <p><input type="radio" class="checkedArtist" name="checkedArtist" id="{{ artist.id }}" value="{{ artist.id }}">{{ artist.name }} </p>
                            </li>
                        {% endfor %}
                    
                    <button class="getAlbums" name="getAlbums" type="submit">Get Albums</button>
                    {% if flags.0 == True %}
                        {% for album in albums %}
                            <li class='album_item'>
                                <label for="{{ album.id }}"></label>
                                <p><input type="checkbox" class="checkedAlbums" name="checkedAlbums" id="{{ album.id }}" value="{{ album.id }}">{{ album.name }}</p>
                                
                            </li>
                        {% endfor %}

                        <button class="getTracks" name="getTracks" type="submit">Get Tracks</button>
                    {% endif %}
                        
                    {% if flags.1 == True %}
                        <h2> Tracks </h2>
                        {% for album in albums %}
                            <h3>Album: {{ album.name }} </h3>
                        
                            {% for track in tracks %}                                              
                                <li class='track_item'>
                                    <label for="{{ track.id }}"></label>
                                    <p><input type="checkbox" class="checkedTracks" name="checkedTracks" id="{{ track.id }}" value="{{ track.id }}">{{ track.name }} - {{ track.artist }} - {{ track.album }}</p>
                                    <p>
                                </li>
                            {% endfor %}
                        {% endfor %}
                        <button type="button" onclick=OpenPopUp() style="width:auto;">Add Songs to Playlist</button> 
                    {% endif %}
                </div>

            {% elif category.name == 'Album' %}
                <div>
                    
                    {% if flags.0 == True %}
                        <h3>Albums - Artists</h3>
                        {% for album in albums %}
                            <li class='album_item'>
                                <label for="{{ album.id }}"></label>
                                <p><input type="checkbox" class="checkedAlbums" name="checkedAlbums" id="{{ album.id }}" value="{{ album.id }}">{{ album.name}} - {{ album.artist}}</p> 
                            </li>
                        {% endfor %}
                    {% endif %}
                    
                    <button class="getTracks" name="getTracks" type="submit">Get Tracks</button>
                    {% if flags.1 == True %}
                        {% for album in albums %}
                            <h3>Album: {{ album.name }} </h3>
                        
                            {% for track in tracks %}                                              
                                <!-- {# if track.album != curr_album %} -->
                                <!-- {# curr_album=track.album #} -->
                                <!-- <h3>Album: {{ track.album }} </h3> -->
                            {# endif #}                      
                                <li class='track_item'>
                                    <label for="{{ track.id }}"></label>
                                    <p><input type="checkbox" class="checkedTracks" name="checkedTracks" id="{{ track.id }}" value="{{ track.id }}">{{ track.name }} - {{ track.artist }} - {{ track.album }}</p>
                                    <p>
                                </li>
                            {% endfor %}
                        {% endfor %}
                        <button type="button" onclick=OpenPopUp() style="width:auto;">Add Songs to Playlist</button>
                    {% endif %}
                </div>
                
            {% endif %}
        {% endif %}

        <div id="id01" class="modal"> 
            <!-- <span onclick="document.getElementById('id01').style.display='none'" class="close" title="Close Modal">X</span>  -->
            <div class="modal-content animate"> 
                <div class="container"> 
                    <label><b>PLaylists</b></label> 
                    <div class="playlists">
                        {% for playlist in playlists %}
                            <input type="checkbox" name = "checkedPlaylists" value="{{ playlist.name }}"/> {{ playlist.name}} <br/>
                        {% endfor%}
                        <div class="clearfix">
                            <button type="button" onclick="openText()" id="AddPlaylist" class="AddPlaylist">Create a new Playlist</button> 
                        </div>
                    </div>
                    <div class="clearfix"> 
                        <button type="button" onclick="document.getElementById('id01').style.display='none'" class="cancelbtn">Cancel</button> 
                        <button type="submit" class="AddSong" name="AddSong">Add Songs</button> 
                    </div> 
                </div> 
            </div> 
        </div> 

    </form>
    
    <!-- <div id="id01" class="modal"> 
        <!-- <span onclick="document.getElementById('id01').style.display='none'" class="close" title="Close Modal">X</span>
        <form class="modal-content animate" action=""> 
            <div class="container"> 
                <label><b>PLaylists</b></label> 
                <div class="playlists">
                    {% for playlist in playlists %}
                        <input type="checkbox" name = "checkedPlalyists"/> {{ playlist.name}} <br/>
                    {% endfor%}
                    <div class="clearfix"></div>
                        <button type="button" onclick="openText()" id="AddPlaylist" class="AddPlaylist">Create a new Playlist</button> 
                    </div>
                </div>
                <div class="clearfix"> 
                    <button type="button" onclick="document.getElementById('id01').style.display='none'" class="cancelbtn">Cancel</button> 
                    <button type="submit" class="AddSong" name="AddSong">Add Songs</button> 
                </div> 
            </div> 
        </div> 
    </div>  -->
    
    <script>
        
        function regenerateButton() {
            var t = document.querySelector('#NewPlaylist');
            var b = document.createElement('button');
            b.type = "button";
            b.addEventListener("click", function () {openText()});
            b.innerHTML = "Create a new Playlist";
            b.id="AddPlaylist";
            b.className="AddPlaylist";
            b.name="AddPlaylist";
            t.parentNode.replaceChild(b,t);
        }

        function openText() {
            var b = document.querySelector('#AddPlaylist');
            var t = document.createElement('input');
            t.placeholder = "Playlist Name....";
            t.className="NewPlaylist";
            t.id="NewPlaylist";
            t.name="NewPlaylist";
            b.parentNode.replaceChild(t,b);
        }

        function OpenPopUp() {
            document.getElementById('id01').style.display='block';


            if (document.querySelector('.AddPlaylist') != null)
                console.log(document.querySelector('.AddPlaylist'))
                regenerateButton();
        }

        // function showContent() {

        //     const template = document.getElementsByTagName("template")[0];
        //     const node = document.importNode(template.content, true);
        //     document.body.appendChild(node);

        //     if (document.querySelector('.AddPlaylist') != null)
        //         console.log(document.querySelector('.AddPlaylist'))
        //         regenerateButton();
        // }

        var modal = document.getElementById('id01'); 
  
        window.addEventListener("click",function(event) { 
            if (event.target == modal) { 
                modal.style.display = "none"; 
            } 
        } ) 
    </script>

</body>
</html>

templates/playlists.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Playlists</title>
</head>
<body>
  <a href="{% url 'OfflinePlaylist:index' %}"><button>Download Music</button></a>
  {% load static %}
  <form action="" method="POST">
    {% csrf_token %}
    <div class="contianter">
      <div style="width: 20%; float: left;" class="PlasylistDisplay">
        <h2>Playlists</h2>
        <div class="list">
          {% for playlist in playlists %}
            <li class="listItem" name="listItem"> <button class="ViewPlaylist" name="ViewPlaylist" value="{{ playlist.name }}" type="submit"> {{ playlist.name }} </button> </li>
          {% endfor %}
        </div>
      </div>
      <div style="width: 80%; float: right;" class="SongDisplay">
        {% if songs|length > 0 %}
          <h2>Playlist: {{ playlistName }}</h2>
          <h3>Name - Artist - Album</h3>
          {% for song in songs %}  
          <ul style="list-style-type: none;">
            <li style="width:100%">
              <div class="SongItem" style="width: 100%; height: 40px; margin:0; padding:3;">
                <div class="SongName" style = "width:50%; height:100%; float:left;">
                  <p class="SongId" style="margin:0;">{{song.track_name}} - {{song.artist_name}} - {{song.album_name}}</p> 
                </div>
                <div class="ModifySong" style = "width:50%; height:100%; float:right; padding:1">
                  {% if song.downloaded == False %}
                    <div class="DownloadSong" style = "height:100%; margin-right: 5px; float:right;">
                      <button type="submit" class="downloadSong" name="downloadSong" value="{{ song.id }}"> Download </button>
                    </div>
                  {% else %}
                    <div class="PlaySong" style = "height:100%; margin: 2px;  float:right;">
                      <button type="submit" id="playSong" class="playSong" name="ViewS" value="{{ song.id }}"> Play </button>
                    </div>
                  {% endif %}
                  <div class="DeleteSong" style = "height:100%; margin: 2px; float:right;">
                    <button type="submit" class="deleteSong" name="deleteSong" value="{{ song.id }}"> Delete </button>
                  </div>
                  <!-- <div class="CloseAudio" id="CloseAudio" style="width:7%; height:100%; float:left; display:none;">
                    <button type="button" onclick="closeAudioControls()"> X </button>
                  </div> -->
                </div>
              </div>
            </li>
          </ul>
          {% endfor %}
        {% else %}
          <h2>Playlist View</h2>
          <p>Add songs to playlist... </p>
        {% endif %}
      </div>
    </div>
  </form>
  <script>
    // function enableControls(){
    //   var a = document.getElementById("audio");
    //   a.style.display = 'block';
    //   var b = document.getElementById("CloseAudio");
    //   b.style.display = 'block';
    //   var audio = document.getElementById("Controls")
    //   audio.pause();
    // }
    // function closeAudioControls(){
    //   var b = document.getElementById("CloseAudio");
    //   b.style.display = 'none';
    //   var a = document.getElementById("audio");
    //   a.style.display = 'none';
    //   var audio = document.getElementById("Controls")
    //   audio.pause();
    // }
  </script>
</body>
</html>

templates/song_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% load static %}
    <audio controls>
        <source src="{% static song_link %}" type="audio/mp4">
        <!-- <source src="horse.mp3" type="audio/mpeg"> -->
    Your browser does not support the audio element.
    </audio>
    
</body>
</html>

templates/test.html
<!DOCTYPE html>

<style> 
    /*add full-width input fields*/ 
    input[type=text], 
    input[type=password] { 
        width: 100%; 
        padding: 12px 20px; 
        margin: 8px 0; 
        display: inline-block; 
        border: 2px solid #ccc; 
        box-sizing: border-box; 
    } 
    /* set a style for all buttons*/ 
    /* button { 
        background-color: green; 
        color: white; 
        padding: 14px 20px; 
        margin: 8px 0; 
        cursor: pointer; 
        width: 100%; 
    }  */
    /*set styles for the cancel button*/ 
    /* .cancelbtn { 
        padding: 14px 20px; 
        background-color: #FF2E00;  
    } */
    /*float cancel and signup buttons and add an equal width*/ 
    .cancelbtn, 
    .signupbtn { 
        float: left; 
        width: 50% 
    } 
    /*add padding to container elements*/ 
    .container { 
        padding: 16px; 
    } 
    /*define the modal’s background*/ 
      
    .modal { 
        display: none; 
        position: fixed; 
        z-index: 1; 
        left: 0; 
        top: 0; 
        width: 100%; 
        height: 100%; 
        overflow: auto; 
        background-color: rgb(0, 0, 0); 
        background-color: rgba(0, 0, 0, 0.8); 
        padding-top: 60px; 
    } 
    /*define the modal-content background*/ 
    
    .modal-content { 
        background-color: #fefefe; 
        margin: 5% auto 15% auto; 
        border: 1px solid #888; 
        width: 80%; 
    } 
    /*define the close button*/ 
      
    /* .close { 
        position: absolute; 
        right: 35px; 
        top: 15px; 
        color: #000; 
        font-size: 40px; 
        font-weight: bold; 
    }  */
    /*define the close hover and focus effects*/ 
      
    /* .close:hover, 
    .close:focus { 
        color: red; 
        cursor: pointer; 
    }  */
      
    .clearfix::after { 
        content: ""; 
        clear: both; 
        display: table; 
    }

    .playlists { 
        border:2px solid #ccc;
        width:300px;
        height: 100px;
        overflow-y: scroll; 
    } 
      
    /* @media screen and (max-width: 300px) { 
        .cancelbtn, 
        .signupbtn { 
            width: 100%; 
        } 
    }*/
</style> 

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% load static %}
    <h2> Playlist Form</h2> 
    <!--Step 1:Adding HTML-->
    <button onclick=OpenPopUp() style="width:auto;">Sign Up</button> 
    <div id="id01" class="modal"> 
        <!-- <span onclick="document.getElementById('id01').style.display='none'" class="close" title="Close Modal">X</span>  -->
        <form class="modal-content animate" action="">
            {% csrf_token %}
            <div class="container"> 
                <label><b>PLaylists</b></label> 
                <div class="playlists">
                    {% for playlist in playlists %}
                        <input type="checkbox" name = "checkedPlalyists"/> {{ playlist.name}} <br/>
                    {% endfor%}
                    <div class="clearfix"></div>
                        <button type="button" onclick="openText()" id="AddPlaylist" class="AddPlaylist">Create a new Playlist</button> 
                    </div>
                </div>
                <div class="clearfix"> 
                    <button type="button" onclick="document.getElementById('id01').style.display='none'" class="cancelbtn">Cancel</button> 
                    <button type="submit" class="signupbtn">Add Songs</button> 
                </div> 
            </div> 
        </form> 
        <audio controls>
            <!-- <source src="{%static "downloaded_songs/J Han - A Breath (featCL & Sam Ock).mp4" %}" type="audio/mpeg"> -->
            {% with 'downloaded_songs/'|add:'Mac Miller - Cinderella (feat Ty Dolla $ign)'|add:'.mp4' as audio_static %}
            <source src="{%static audio_static %}" type="audio/mpeg">
            {% endwith %}
        </audio>
    </div>
    

    
    <!--close the modal by just clicking outside of the modal-->
    <script>
        
        function regenerateButton() {
            var t = document.querySelector('#NewPlaylist');
            var b = document.createElement('button');
            b.type = "button";
            b.addEventListener("click", function () {openText()});
            b.innerHTML = "Create a new Playlist";
            b.id="AddPlaylist";
            b.className="AddPlaylist";
            t.parentNode.replaceChild(b,t);
        }

        function openText() {
            var b = document.querySelector('#AddPlaylist');
            var t = document.createElement('input');
            t.placeholder = "Playlist Name....";
            t.class="NewPlaylist";
            t.id="NewPlaylist";
            b.parentNode.replaceChild(t,b);
        }

        function OpenPopUp() {
            document.getElementById('id01').style.display='block';

            if (document.querySelector('.AddPlaylist') != null)
                console.log(document.querySelector('.AddPlaylist'))
                regenerateButton();
        }

        var modal = document.getElementById('id01'); 
  
        window.addEventListener("click",function(event) { 
            if (event.target == modal) { 
                modal.style.display = "none"; 
            } 
        } ) 
    </script> 

    
</body>
</html>